# Generated by Django 2.2.6 on 2019-11-04 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment_to_comment',
            name='post_ctc_id',
        ),
    ]
